name: "Release"

on:
  release:
    types: [ published ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
